# =======================================================================
# E2E Website Tests Workflow
# =======================================================================
#
# This workflow runs end-to-end tests for the console-table-printer website
# using Playwright.
#
# It performs:
# - Website navigation tests
# - Content verification tests
# - Documentation page tests
#
# The workflow runs:
# - Hourly (via cron)
# - On push to main branch
# - Manually via workflow_dispatch
#
# Test results are uploaded as artifacts and stored for 7 days.
# =======================================================================

name: E2E Website Tests

on:
  schedule:
    # Run every hour
    - cron: '0 * * * *'
  # Also run on push to main branch
  push:
    branches: [ main ]
  # Allow manual triggering
  workflow_dispatch:

jobs:
  e2e-tests:
    name: E2E Website Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install

      - name: Install Playwright browsers
        run: npx playwright install --with-deps chromium

      - name: Run E2E tests
        run: yarn test:e2e
        continue-on-error: true  # Continue workflow even if E2E tests fail, but mark step as failed

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: e2e-test-results
          path: |
            playwright-report/
            test-results/
          retention-days: 7 