# =======================================================================
# Unit Tests Workflow
# =======================================================================
#
# This workflow runs unit tests for the console-table-printer and simple-wcswidth 
# packages on multiple Node.js versions (18.x, 20.x, 22.x, 24.x).
#
# It performs:
# - Unit tests on all supported Node.js versions
#
# The workflow runs:
# - Hourly (via cron)
# - On push to main branch
# - Manually via workflow_dispatch
#
# =======================================================================

name: Unit Tests

on:
  schedule:
    # Run every hour
    - cron: '0 * * * *'
  # Also run on push to main branch
  push:
    branches: [ main ]
  # Allow manual triggering
  workflow_dispatch:

jobs:
  unit-tests:
    name: Unit Tests (Node ${{ matrix.node-version }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x, 24.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install

      - name: Run unit tests
        run: yarn test:unit 